language: java
before_install:
  - sudo add-apt-repository ppa:v-kukol/mono-3
  - sudo apt-get update -qq
  - sudo apt-get install -qq mono-xsp4
  - mono --version
sudo: true
jdk:
- oraclejdk8
- oraclejdk7

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
- ./gradlew paketInstall --info
