language: java

sudo: true

os:
  - linux
  - osx

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
- oraclejdk8
- oraclejdk7

addons:
  apt:
    packages:
      - mono-xsp4

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mono; fi

script:
- ./gradlew paketInstall --info
