language: java

sudo: true

matrix:
  include:
    - os: linux
      sudo: true
      jdk: oraclejdk8
    - os: linux
      sudo: true
      jdk: oraclejdk7
    - os: osx
      osx_image: xcode7.2
    - os: osx
      osx_image: xcode8.3
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - ./travis/setup_$TRAVIS_OS_NAME.sh
  - mono --version

script:
- ./gradlew publish-TestPackage --info
