language: java

sudo: true

os:
  - linux
  - osx

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
- oraclejdk8
- oraclejdk7

addons:
  apt:
    packages:
      - mono-xsp4

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mono; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:directhex/monoxide -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install mono-xsp4; fi


script:
- ./gradlew paketInstall --info
